matrix:
  include:

    - language: java
      jdk: openjdk9
      sudo: false
      before_script:
        - cd pipeline/pipeline-entry
      script:
        - mvn clean install

    - language: python
      python: 3.4
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          update: true

      before_install:
        - sudo apt-get update -qq
      install:
        - .travis/install.sh
      before_script:
        - .travis/login.sh
      script:
        - .travis/test.sh